export const mentorData = [
     {
    id: 1,
    name: "Hemant Raj",
    degree: "B.Tech CSE",
    graduationYear: "2025",
    email: "hemant@gmail.com",
    contact: "1234567890",
    about: "A tech-enthusiast currently working at XYZ company at ABC place.",
    skills: ["Web-dev", "App-dev", "Machine Learning"],
    linkedin: "http://example.com",
    photo: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop"
  },
  {
    id: 2,
    name: "Sarah Johnson",
    degree: "B.Tech Computer Science",
    graduationYear: "2025",
    email: "sarah.johnson@gmail.com",
    contact: "9876543210",
    about: "A tech-enthusiast currently working at XYZ company at ABC place.",
    skills: ["Web-dev", "App-dev", "Machine Learning"],
    linkedin: "https://linkedin.com/in/sarahjohnson",
    photo: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop"
  },
  {
    id: 3,
    name: "Michael Chen",
    degree: "B.Tech Mechanical",
    graduationYear: "2024",
    email: "michael.chen@gmail.com",
    contact: "5551234567",
    about: "A mechanical engineer specializing in automotive design and sustainable energy solutions.",
    skills: ["AutoCAD", "SolidWorks", "3D Printing"],
    linkedin: "https://linkedin.com/in/michaelchen",
    photo: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop"
  },
  // {
  //   id: 4,
  //   name: "Priya Sharma",
  //   degree: "B.Tech Electronics",
  //   graduationYear: "2024",
  //   email: "priya.sharma@gmail.com",
  //   contact: "7890123456",
  //   about: "Electronics engineer with a focus on IoT solutions and embedded systems development.",
  //   skills: ["C/C++", "Arduino", "IoT"],
  //   linkedin: "https://linkedin.com/in/priyasharma",
  //   photo: "https://images.pexels.com/photos/3785077/pexels-photo-3785077.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop"
  // },
  {
    id: 5,
    name: "David Martinez",
    degree: "B.Tech Civil",
    graduationYear: "2022",
    email: "david.martinez@gmail.com",
    contact: "3216549870",
    about: "Civil engineer committed to sustainable infrastructure development and smart city planning.",
    skills: ["AutoCAD", "Revit", "Project Planning"],
    linkedin: "https://linkedin.com/in/davidmartinez",
    photo: "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop"
  },
  {
    id: 6,
    name: "Emily Rodriguez",
    degree: "B.Tech Information Technology",
    graduationYear: "2023",
    email: "emily.rodriguez@gmail.com",
    contact: "9998887776",
    about: "IT professional specializing in cybersecurity and data analytics with passion for digital security.",
    skills: ["Cybersecurity", "Data Analysis", "Python"],
    linkedin: "https://linkedin.com/in/emilyrodriguez",
    photo: "https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop"
  },
  {
    id: 7,
    name: "James Wilson",
    degree: "B.Tech Electrical",
    graduationYear: "2021",
    email: "james.wilson@gmail.com",
    contact: "4567891230",
    about: "Electrical engineer working on renewable energy projects and smart grid technologies.",
    skills: ["MATLAB", "Power Systems", "Renewable Energy"],
    linkedin: "https://linkedin.com/in/jameswilson",
    photo: "https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop"
  },
  {
    id: 8,
    name: "Lisa Thompson",
    degree: "B.Tech Chemical",
    graduationYear: "2023",
    email: "lisa.thompson@gmail.com",
    contact: "6789012345",
    about: "Chemical engineer focused on process optimization and environmental sustainability in manufacturing.",
    skills: ["Process Design", "ASPEN", "Environmental Engineering"],
    linkedin: "https://linkedin.com/in/lisathompson",
    photo: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop"
  },
  {
    id: 9,
    name: "Robert Kumar",
    degree: "B.Tech Aerospace",
    graduationYear: "2023",
    email: "robert.kumar@gmail.com",
    contact: "8901234567",
    about: "Aerospace engineer passionate about aircraft design and space exploration technologies.",
    skills: ["CATIA", "Aerodynamics", "Flight Dynamics"],
    linkedin: "https://linkedin.com/in/robertkumar",
    photo: "https://images.pexels.com/photos/2182969/pexels-photo-2182969.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop"
  },
  {
    id: 10,
    name: "Amanda Davis",
    degree: "B.Tech Biotechnology",
    graduationYear: "2022",
    email: "amanda.davis@gmail.com",
    contact: "9012345678",
    about: "Biotechnology engineer working on innovative medical devices and pharmaceutical research.",
    skills: ["Bioprocessing", "Lab Techniques", "Research"],
    linkedin: "https://linkedin.com/in/amandadavis",
    photo: "https://images.pexels.com/photos/1239288/pexels-photo-1239288.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop"
  },
  {
    id: 11,
    name: "Kevin Lee",
    degree: "B.Tech Software",
    graduationYear: "2024",
    email: "kevin.lee@gmail.com",
    contact: "0123456789",
    about: "Software engineer specializing in mobile app development and cloud computing solutions.",
    skills: ["React Native", "AWS", "Node.js"],
    linkedin: "https://linkedin.com/in/kevinlee",
    photo: "https://images.pexels.com/photos/2379003/pexels-photo-2379003.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop"
  },
  {
    id: 12,
    name: "Rachel Green",
    degree: "B.Tech Environmental",
    graduationYear: "2024",
    email: "rachel.green@gmail.com",
    contact: "1357924680",
    about: "Environmental engineer dedicated to water treatment and waste management solutions.",
    skills: ["Water Treatment", "GIS", "Environmental Modeling"],
    linkedin: "https://linkedin.com/in/rachelgreen",
    photo: "https://images.pexels.com/photos/1181689/pexels-photo-1181689.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop"
  },
  {
    id: 13,
    name: "Daniel Brown",
    degree: "B.Tech Petroleum",
    graduationYear: "2022",
    email: "daniel.brown@gmail.com",
    contact: "2468013579",
    about: "Petroleum engineer working on drilling optimization and reservoir management projects.",
    skills: ["Reservoir Simulation", "Drilling", "Petrel"],
    linkedin: "https://linkedin.com/in/danielbrown",
    photo: "https://images.pexels.com/photos/2182968/pexels-photo-2182968.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop"
  },
  {
    id: 14,
    name: "Sophie Miller",
    degree: "B.Tech Industrial",
    graduationYear: "2022",
    email: "sophie.miller@gmail.com",
    contact: "3691470258",
    about: "Industrial engineer focused on supply chain optimization and lean manufacturing processes.",
    skills: ["Six Sigma", "Supply Chain", "Lean Manufacturing"],
    linkedin: "https://linkedin.com/in/sophiemiller",
    photo: "https://images.pexels.com/photos/1239287/pexels-photo-1239287.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop"
  },
  {
    id: 15,
    name: "Alex Turner",
    degree: "B.Tech Robotics",
    graduationYear: "2024",
    email: "alex.turner@gmail.com",
    contact: "4815162342",
    about: "Robotics engineer developing autonomous systems and AI-powered robotic solutions.",
    skills: ["ROS", "Computer Vision", "AI"],
    linkedin: "https://linkedin.com/in/alexturner",
    photo: "https://images.pexels.com/photos/2379001/pexels-photo-2379001.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop"
  },
  {
    id: 16,
    name: "Maya Patel",
    degree: "B.Tech Textile",
    graduationYear: "2025",
    email: "maya.patel@gmail.com",
    contact: "5927384061",
    about: "Textile engineer innovating in smart fabrics and sustainable textile manufacturing processes.",
    skills: ["Fabric Design", "Sustainability", "Quality Control"],
    linkedin: "https://linkedin.com/in/mayapatel",
    photo: "https://images.pexels.com/photos/1181687/pexels-photo-1181687.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop"
  },
  // {
  //   id: 17,
  //   name: "Chris Anderson",
  //   degree: "B.Tech Marine",
  //   graduationYear: "2022",
  //   email: "chris.anderson@gmail.com",
  //   contact: "6048271359",
  //   about: "Marine engineer specializing in ship design and offshore engineering solutions.",
  //   skills: ["Ship Design", "Offshore Engineering", "Naval Architecture"],
  //   linkedin: "https://linkedin.com/in/chrisanderson",
  //   photo: "https://images.pexels.com/photos/2182967/pexels-photo-2182967.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop"
  // },
  // {
  //   id: 18,
  //   name: "Natalie White",
  //   degree: "B.Tech Food Technology",
  //   graduationYear: "2021",
  //   email: "natalie.white@gmail.com",
  //   contact: "7159483620",
  //   about: "Food technologist working on food safety and innovative food processing technologies.",
  //   skills: ["Food Safety", "Processing", "Quality Assurance"],
  //   linkedin: "https://linkedin.com/in/nataliewhite",
  //   photo: "https://images.pexels.com/photos/1239289/pexels-photo-1239289.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop"
  // },
  // {
  //   id: 19,
  //   name: "Ryan Clark",
  //   degree: "B.Tech Mining",
  //   graduationYear: "2024",
  //   email: "ryan.clark@gmail.com",
  //   contact: "8260594731",
  //   about: "Mining engineer focused on sustainable mining practices and mineral processing optimization.",
  //   skills: ["Mining Operations", "Geology", "Safety Management"],
  //   linkedin: "https://linkedin.com/in/ryanclark",
  //   photo: "https://images.pexels.com/photos/2379002/pexels-photo-2379002.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop"
  // },
  {
    id: 20,
    name: "Isabella Garcia",
    degree: "B.Tech Metallurgical",
    graduationYear: "2025",
    email: "isabella.garcia@gmail.com",
    contact: "9371605842",
    about: "Metallurgical engineer specializing in materials science and advanced alloy development.",
    skills: ["Materials Science", "Metallurgy", "Heat Treatment"],
    linkedin: "https://linkedin.com/in/isabellagarcia",
    photo: "https://images.pexels.com/photos/1181688/pexels-photo-1181688.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop"
  }
];
