export const teamMembers = [
    {
    id: 1,
    name: "Yashasvi Shukla",
    role: "Head",
    year: "2023-2027",
    bio: "Building bridges between current students and accomplished alumni mentors.",
    image: "../Team/YashasviShukla.jpeg",
    linkedin: "https://www.linkedin.com/in/yashasvi-shukla-49882030a/",
    github: "/team",
    group: "Head",
    team: "Web Dev",
  },
  {
    id: 2,
    name: "Aviral Sharma",
    role: "Team Lead",
    year: "2023-2027",
    bio: "Delivers end-to-end solutions from UI to database with agility.",
    image: "../Team/AviralSharma.jpg",
    linkedin: "https://www.linkedin.com/in/aviral-sharma-b57127299/",
    github: "https://github.com/AviralSharma11",
    group: "Team Lead",
    team: "Web Dev",
  },
  {
    id: 8,
    name: "Vaatsalya Sahu",
    role: "Front-End Developer",
    year: "2024-2028",
    bio: "Transforms designs into pixel-perfect, interactive web experiences.",
    image: "../Team/VaatsalyaSahu.jpg",
    linkedin: "https://www.linkedin.com/in/vaatsalya-sahu-28274031b",
    github: "https://github.com/Svaatsalya",
    group: "Member",
    team: "Web Dev",
  },
  {
    id: 5,
    name: "Veer Doria",
    role: "Back-End Developer",
    year: "2024-2028",
    bio: "Builds robust server-side logic and APIs for scalable web applications.",
    image: "../Team/VeerDoria.jpg",
    linkedin: "https://www.linkedin.com/in/veer-doria-16567b330/",
    github: "https://github.com/VeerDoria",
    group: "Member",
    team: "Web Dev",
  },
  {
    id: 3,
    name: "Chetan Verma",
    role: "Front-End Developer",
    year: "2024-2028",
    bio: "Crafts seamless and responsive user interfaces with HTML, CSS, and JavaScript.",
    image: "../Team/ChetanVerma.jpg",
    linkedin: "https://in.linkedin.com/in/chetan-verma-a82239324",
    github: "https://github.com/codecv28",
    group: "Member",
    team: "Web Dev",
  },
  {
    id: 4,
    name: "Sarang Thakare",
    role: "Full-Stack Developer",
    year: "2024-2028",
    bio: "Bridges the gap between frontend polish and backend performance.",
    image: "../Team/SarangThakare.png",
    linkedin: "https://linkedin.com/in/sarang-v-thakare",
    github: "https://github.com/SarangVT",
    group: "Member",
    team: "Web Dev",
  },
  
  {
    id: 6,
    name: "Sethumadhav Naik",
    role: "Front-End Developer",
    year: "2024-2028",
    bio: "Focuses on accessibility, performance, and cross-browser compatibility.",
    image: "../Team/SethuMadhavNaik.jpg",
    linkedin: "https://www.linkedin.com/in/bhukya-sethu-madhav-naik-467b96366/",
    github: "https://github.com/Sethu-madhav17",
    group: "Member",
    team: "Web Dev",
  },
  {
    id: 7,
    name: "Devika Manoharan",
    role: "Back-End Developer",
    year: "2024-2028",
    bio: "Back-End developer building the future of alumni engagement platforms.",
    image: "../Team/DevikaManoharan.jpeg",
    linkedin: "https://www.linkedin.com/in/devika-manoharan-12774b330",
    github: "https://github.com/devs1man",
    group: "Member",
    team: "Web Dev",
  },


];
