export const teamMembers = [
  {
    id: 1,
    name: "Vaatsalya Sahu",
    role: "Front-End Developer",
    image: "../Team/VaatsalyaSahu.jpg",
    linkedin: "https://www.linkedin.com/in/vaatsalya-sahu-28274031b",
    insta: "/team",
    group: "Member",
  },
  {
    id: 2,
    name: "Veer Doria",
    role: "Back-End Developer",
    image: "../Team/VeerDoria.jpg",
    linkedin: "https://www.linkedin.com/in/veer-doria-16567b330/",
    insta: "/team",
    group: "Member",
  },
  {
    id: 3,
    name: "Chetan Verma",
    role: "Front-End Developer",
    image: "../Team/ChetanVerma.jpg",
    linkedin: "https://in.linkedin.com/in/chetan-verma-a82239324",
    insta: "/team",
    group: "Member",
  },
  {
    id: 4,
    name: "Sarang Thakare",
    role: "Full-Stack Developer",
    image: "../Team/SarangThakare.png",
    linkedin: "https://linkedin.com/in/sarang-v-thakare",
    insta: "/team",
    group: "Member",
  },
  {
    id: 5,
    name: "Aviral Sharma",
    role: "Full-Stack Developer",
    image: "../Team/AviralSharma.jpg",
    linkedin: "https://www.linkedin.com/in/aviral-sharma-b57127299/",
    insta: "/team",
    group: "Co-Head",
  },
  {
    id: 6,
    name: "Sethumadhav Naik",
    role: "Front-End Developer",
    image: "../Team/SethuMadhavNaik.jpg",
    linkedin: "https://www.linkedin.com/in/bhukya-sethu-madhav-naik-467b96366/",
    insta: "/team",
    group: "Member",
  },
  {
    id: 7,
    name: "Devika Manoharan",
    role: "Back-End Developer",
    image: "../Team/DevikaManoharan.jpeg",
    linkedin: "https://www.linkedin.com/in/devika-manoharan-12774b330",
    insta: "/team",
    group: "Member",
  },
  {
    id: 8,
    name: "Yashasvi Shukla",
    role: "Web Dev",
    image: "../Team/YashasviShukla.jpeg",
    linkedin: "https://www.linkedin.com/in/yashasvi-shukla-49882030a/",
    insta: "/team",
    group: "Head",
  },
  {
    id: 9,
    name: "Anish De",
    role: "Backend Developer",
    image: "../Team/AnishDe.jpg",
    linkedin: "https://www.linkedin.com/in/anish-de-601383375?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    insta: "https://github.com/Anish-gthub",
    group: "Member",
  },
  {
    id: 10,
    name: "Ansh Kyal",
    role: "Overall Head",
    image: "../Team/Ansh Kyal_Head.jpg",
    linkedin: "/team",
    insta: "/team",
    group: "Head",
  },
   {
    id: 11,
    name: "Garvit Mathur",
    role: "Design",
    image: "../Team/Garvit Mathur_Design Head.jpg",
    linkedin: "/team",
    insta: "/team",
    group: "Head",
  },
   {
    id: 12,
    name: "Keshvi Lakhotia",
    role: "Logistics ",
    image: "../Team/Keshvi Lakhotia_Logistics Head.jpg",
    linkedin: "/team",
    insta: "/team",
    group: "Head",
  },
     {
    id: 13,
    name: "Kavyansh Raj Singh",
    role: "Newsletter Coordinator",
    image: "../Team/Kavyansh Raj Singh_Newsletter Coordinator.jpg",
    linkedin: "/team",
    insta: "/team",
    group: "Head",
  },
   {
    id: 14,
    name: "Mohak Dadhich",
    role: " Overall",
    image: "../Team/Mohak Dadhich- Co Head.jpg",
    linkedin: "/team",
    insta: "/team",
    group: "Co-Head",
  },
  {
    id: 15,
    name: "Vedansh Shrivastava",
    role: "ARAM",
    image: "../Team/Vedansh Shrivastava_ARAM Head.jpg",
    linkedin: "/team",
    insta: "/team",
    group: "Head",
  },
  {
    id: 16,
    name: "Anushka Krishan",
    role: " Content",
    image: "../Team/Anushka Krishan_Content Head.jpg",
    linkedin: "/team",
    insta: "/team",
    group: "Head",
  },
   {
    id: 17,
    name: "Aryama Singh",
    role: " Content",
    image: "../Team/Aryama Singh-Content.jpg",
    linkedin: "/team",
    insta: "/team",
    group: "Member",
  },
  {
    id: 18,
    name: "Gopesh Srinivasan ",
    role: " Content",
    image: "../Team/Gopesh Srinivasan-Content.jpg",
    linkedin: "/team",
    insta: "/team",
    group: "Member",
  },
  {
    id: 19,
    name: "Paawni Gulati",
    role: " Content",
    image: "../Team/Paawni Gulati-Content.png",
    linkedin: "/team",
    insta: "/team",
    group: "Member",
  },
    {
    id: 20,
    name: "Mayank Bisaria",
    role: "Design",
    image: "../Team/Mayank Bisaria-Design.jpg",
    linkedin: "/team",
    insta: "/team",
    group: "Member",
  },
  {
    id: 21,
    name: "Md Hassan Ansari",
    role: "Design",
    image: "../Team/Mohd Hassan Raza Kalim Ansari-Design.jpg",
    linkedin: "/team",
    insta: "/team",
    group: "Member",
  },
  {
    id: 22,
    name: "Anwesh Mal",
    role: "Design",
    image: "../Team/Anwesh Mal-Design .jpg",
    linkedin: "/team",
    insta: "/team",
    group: "Member",
  },
  {
    id: 23,
    name: "Kanishk Singh",
    role: "Design",
    image: "../Team/Kanishk Singh-Design.jpg ",
    linkedin: "/team",
    insta: "/team",
    group: "Member",
  },
  {
    id: 24,
    name: "Ankita Yadav",
    role: "Design",
    image: "../Team/Ankita Yadav-Design.jpg",
    linkedin: "/team",
    insta: "/team",
    group: "Member",
  },
    {
    id: 25,
    name: "Anushka Jain",
    role: "Design",
    image: "../Team/Anushka Jain-Design.jpeg",
    linkedin: "/team",
    insta: "/team",
    group: "Member",
  },
  {
    id: 26,
    name: "Ankita Yadav",
    role: "Design",
    image: "../Team/Ankita Yadav-Design.jpg",
    linkedin: "/team",
    insta: "/team",
    group: "Member",
  },
];

