name = "acellcdn"
main = "index.js"
compatibility_date = "2026-08-27"
preview_urls = false

[cache]
enabled = true
cross_version_cache = true

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "acellmedia"